version: '3.7'

services:

  todo-app:
    container_name: todo-app
    build:
      context: './client'
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

networks:
    app-network:
        driver: bridge