# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: MasterDeployCI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Enter client folder
      run: cd ./client/
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: npm run deploy
    - name: Updating Domain
      run: echo "Update domain"
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "ashcherbakov@fevo.com"
        git config --global user.name "cyberduck1"
        git remote set-url origin https://a4a83e30064cdd5f498773aa16dc33f4adad466c@github.com/your_github_username>/your_repo>.git
        npm run deploy
