name: Cypress tests

on: push

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

#      - name: Install wait-on
#        run: npm install wait-on

      - name: Start GW
        working-directory: ./gateway
        run: yarn && yarn run start &

      - name: Start Client
        uses: ./
        with:
          working-directory: ./client
          wait-on: 'http://localhost:4001'
          run: yarn && yarn start &

      - name: Cypress tests
        uses: ./
        with:
          working-directory: ./
          wait-on: 'http://localhost:3000'
          build: npm run build
          start: npm start
